### ISSUE TITLE
xo-server fails to start

### ISSUE THREAD

**Issue by bitratio** [ronivay/XenOrchestraInstallerUpdater#205] opened 2024-01-19 19:47 UTC
**OS Version**: Ubuntu 22.04/20.04 + Debian 12
**Node.js version**: v18.19.0
**Yarn version**: 1.22.19

**Server specs**
4 vCPU 8GiB

**Issue**
xo-server fails to start after installation

[info] Starting xo-server...
 waiting for port to be open
 waiting for port to be open
 waiting for port to be open
 waiting for port to be open
 waiting for port to be open
 waiting for port to be open

[fail] Installation completed, but looks like there was a problem when starting xo-server. Check /opt/XenOrchestraInstallerUpdater/logs/xo-install.log-202401191937 for more details

Jan 19 19:40:05 xoa-ce xo-server[11010]: /opt/xo/xo-builds/xen-orchestra-202401191937/@vates/decorate-with/index.js:25
Jan 19 19:40:05 xoa-ce xo-server[11010]:       descriptor.value = applyDecorator(decorator, descriptor.value)
Jan 19 19:40:05 xoa-ce xo-server[11010]:                                                               ^
Jan 19 19:40:05 xoa-ce xo-server[11010]: TypeError: Cannot read properties of undefined (reading 'value')
Jan 19 19:40:05 xoa-ce xo-server[11010]:     at decorateObject (/opt/xo/xo-builds/xen-orchestra-202401191937/@vates/decorate-with/index.js:25:63)
Jan 19 19:40:05 xoa-ce xo-server[11010]:     at file:///opt/xo/xo-builds/xen-orchestra-202401191937/packages/xo-server/dist/xapi/mixins/patching.mjs:450:16
Jan 19 19:40:05 xoa-ce xo-server[11010]:     at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
Jan 19 19:40:05 xoa-ce xo-server[11010]:     at async ModuleLoader.import (node:internal/modules/esm/loader:336:24)
Jan 19 19:40:05 xoa-ce xo-server[11010]:     at async loadESM (node:internal/process/esm_loader:34:7)
Jan 19 19:40:05 xoa-ce xo-server[11010]:     at async handleMainPromise (node:internal/modules/run_main:106:12)
Jan 19 19:40:05 xoa-ce xo-server[11010]: Node.js v18.19.0

**Installation logfile**
Attach complete log as a file.

**Comment by Mike-Bros** [comment] 2024-01-19 20:20
Hey there, I was working on a vagrant box using this last night and was pretty meticulous in documenting my steps. When trying to reproduce steps today with some automation added to my `Vagrantfile`, I noticed this issue. I tried to revert changes to no avail and have gone through several fresh vagrant boxes testing this, and this is my summary.

### Environment Details
- **Operating System**: Debian 12
- **Node.js Version**: v18.19.0
- **Yarn Version**: 1.22.19
- **Server Specs**: 4 vCPU, 8GiB RAM

### Issue Description
The `xo-server` fails to start after installation using the XenOrchestraInstallerUpdater script. The server repeatedly waits for the port to open, as indicated by the logs, but eventually fails.

### Error Messages
```
The primary error found in the logs is a TypeError related to object decoration:
TypeError: Cannot read properties of undefined (reading 'value')
at decorateObject (/opt/xo/xo-builds/xen-orchestra-202401191937/@vates/decorate-with/index.js:25:63)
```

### Steps Tried
1. **Verified Node.js Compatibility**: Using Node.js version v18.19.0 as per the installation script's configuration.
2. **Checked for Open Ports**: Ran `netstat` to ensure no other service was occupying port 443; no conflicts found.
3. **Reviewed `Vagrantfile`**: Adjusted network configurations and port forwarding settings, tested multiple variations ~10 boxes.
4. **Reinstallations and Rebuilds**: Attempted several times but encountered the same error.
5. **Reviewed GitHub Issues**: Found this issue haha

**Comment by ronivay** [comment] 2024-01-19 20:47
This is probably due to some recent commit to xen-orchestra master branch. I have a hunch which one it is but i can't test myself until tomorrow.

In the meanwhile you can try to set `BRANCH="ec1669a"` in `xo-install.cfg` and run `xo-install --update` to see if my best guess is correct :)

**Comment by bitratio** [comment] 2024-01-19 21:35
That sorted it @ronivay - thanks!

**Comment by ronivay** [comment] 2024-01-19 21:40
> That sorted it @ronivay - thanks! 
> 
> 
> 
> Now I get connection refused from browser though...

Great. Will keep this issue open until it's sorted. That branch setting should be put back to "master" once it works again, otherwise later updates won't do anything.

Can you run `curl -L -I http://127.0.0.1` on the server where you installed xo. If it gives HTTP status 200, this sounds like you may have a firewall blocking the connection from your browser towards the xo installation.

**Comment by bitratio** [comment] 2024-01-19 21:47
Sorted. Listening on ipv6 only!

**Comment by Mike-Bros** [comment] 2024-01-19 21:56
Just changing the `BRANCH="ec1669a"` worked for me thanks @ronivay!

**Comment by ronivay** [comment] 2024-01-19 21:56
> Sorted. Listening on ipv6 only! 
> 
> 
> 
> Curious that it doesn't bind to both....

Nice. Yeah that's actually a feature of xo-server, it listens to all v6 addresses if available and v4 otherwise. I should probably add a config option to define the listen address manually as now it just uses the default behaviour.

**Comment by ronivay** [comment] 2024-01-20 09:33
Bug is now fixed and you should switch BRANCH back to master before running update again to get to the latest version.

Will handle that listen address config option separately.

**Closed by ronivay** 2024-01-20 09:33 UTC
