### ISSUE TITLE
xo-install.sh fails with remote defined.

### ISSUE THREAD

**Issue by lastcmaster** [ronivay/XenOrchestraInstallerUpdater#196] opened 2023-10-26 15:45 UTC
**OS Version**: Debian GNU/Linux 11 (bullseye)  5.10.0-25-amd64 #1 SMP Debian 5.10.191-1 (2023-08-16) x86_64 GNU/Linux
**Node.js version**: v18.17.1
**Yarn version**:  1.22.19

**Server specs**
2CPU and 8GiB

**Issue**
When doing an update (option 2) on a system with an NFS file system remote, the script fails when I tries to change owner on the imported file system. Stopping the server does not umount the file system.

**Installation logfile**
Attach complete log as a file. 

[xo-install.log-202310261737.gz](https://github.com/ronivay/XenOrchestraInstallerUpdater/files/13179704/xo-install.log-202310261737.gz)

**Comment by ronivay** [comment] 2023-10-30 09:22
Hi,

Thanks for reporting. I'm not able to reproduce this with an NFS remote, it gets umounted when xo-server is stopped, before chown is ran. Could there be something in your case which is preventing the umount from happening?

Anyway i guess this can be solved by not running recursive chown to the mounts dir.

**Comment by ronivay** [comment] 2023-10-30 09:30
Please give update a shot with the one from feature branch: https://github.com/ronivay/XenOrchestraInstallerUpdater/tree/fix/nfs-remote-permissions

**Comment by lastcmaster** [comment] 2023-10-30 11:22
Hi,

I don’t think so. My current workaround is to run the script until fail and then umount the remote nfs and re-run the script. So as soon as the xo-server is down, the mount is not busy and allows the umount to run.

**Comment by lastcmaster** [comment] 2023-10-30 11:28
Hi,

This works, I can run an update without problem with the remote mounted.

Thanks.

**Comment by ronivay** [comment] 2023-10-30 12:22
Great. I'll merge that and close this. Should've probably leave out the recursive option in the first place, but good that you encountered this. Thanks.

**Closed** 2023-10-30 12:22 UTC
